#use: mkmf -t Makefile.template -p nbo.exe
#to generate a proper makefile

MODULE_PATH=/opt/intel/compilers_and_libraries_2019.3.199/mac/mkl/lib

FC=ifort
LD=ifort
#FFLAGS=-check all -check noarg_temp_created -g -traceback -warn unused -I $(MODULE_PATH)
FFLAGS= -qopenmp -I/opt/intel/compilers_and_libraries_2019.3.199/mac/mkl/include/intel64/lp64 -heap-arrays 64
LDFLAGS=-L$(MODULE_PATH) -lmkl_core -lmkl_intel_lp64 -lmkl_sequential -lmkl_blas95_lp64 -lmkl_lapack95_lp64 -qopenmp
